export const ORDER_CREATE_REQUEST = 'ORDER_CREATE_REQUEST';
export const ORDER_CREATE_SUCCESS = 'ORDER_CREATE_SUCCESS';
export const ORDER_CREATE_FAIL = 'ORDER_CREATE_FAIL';
export const ORDER_CREATE_RESET = 'ORDER_CREATE_RESET';

export const ORDER_DETAILS_REQUEST = 'ORDER_DETAILS_REQUEST';
export const ORDER_DETAILS_SUCCESS = 'ORDER_DETAILS_SUCCESS';
export const ORDER_DETAILS_FAIL = 'ORDER_DETAILS_FAIL';
export const ORDER_DETAILS_RESET = 'ORDER_DETAILS_RESET';

export const ORDER_PAY_REQUEST = 'ORDER_PAY_REQUEST';
export const ORDER_PAY_SUCCESS = 'ORDER_PAY_SUCCESS';
export const ORDER_PAY_FAIL = 'ORDER_PAY_FAIL';
export const ORDER_PAY_RESET = 'ORDER_PAY_RESET';

export const ORDER_LIST_FOR_USER_REQUEST = 'ORDER_LIST_FOR_USER_REQUEST';
export const ORDER_LIST_FOR_USER_SUCCESS = 'ORDER_LIST_FOR_USER_SUCCESS';
export const ORDER_LIST_FOR_USER_FAIL = 'ORDER_LIST_FOR_USER_FAIL';
export const ORDER_LIST_FOR_USER_RESET = 'ORDER_LIST_FOR_USER_RESET';

export const ORDER_LIST_FOR_ADMIN_REQUEST = 'ORDER_LIST_FOR_ADMIN_REQUEST';
export const ORDER_LIST_FOR_ADMIN_SUCCESS = 'ORDER_LIST_FOR_ADMIN_SUCCESS';
export const ORDER_LIST_FOR_ADMIN_FAIL = 'ORDER_LIST_FOR_ADMIN_FAIL';
export const ORDER_LIST_FOR_ADMIN_RESET = 'ORDER_LIST_FOR_ADMIN_RESET';

export const ORDER_SET_SHIPPING_REQUEST = 'ORDER_SET_SHIPPING_REQUEST';
export const ORDER_SET_SHIPPING_SUCCESS = 'ORDER_SET_SHIPPING_SUCCESS';
export const ORDER_SET_SHIPPING_FAIL = 'ORDER_SET_SHIPPING_FAIL';
export const ORDER_SET_SHIPPING_RESET = 'ORDER_SET_SHIPPING_RESET';
